## Preprocessing

In [2]:
import pandas as pd
import regex as re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [5]:
# prompts_df = pd.read_csv('prompts_train.csv')
prompts_df = pd.read_csv('../data/eval_student_summaries/summaries_train.csv')
prompts_df

,student_id,prompt_id,text,content,wording
0,000e8c3c7ddb,814d6b,The third wave was an experimentto see how peo...,0.205683,0.380538
1,0020ae56ffbf,ebad26,They would rub it up with soda to make the sme...,-0.548304,0.506755
2,004e978e639e,3b9047,"In Egypt, there were many occupations and soci...",3.128928,4.231226
3,005ab0199905,3b9047,The highest class was Pharaohs these people we...,-0.210614,-0.471415
4,0070c9e7af47,814d6b,The Third Wave developed rapidly because the ...,3.272894,3.219757
...,...,...,...,...,...
7160,ff7c7e70df07,ebad26,They used all sorts of chemical concoctions to...,0.205683,0.380538
7161,ffc34d056498,3b9047,The lowest classes are slaves and farmers slav...,-0.308448,0.048171
7162,ffd1576d2e1b,3b9047,they sorta made people start workin...,-1.408180,-0.493603
7163,ffe4a98093b2,39c16e,An ideal tragety has three elements that make ...,-0.393310,0.627128
7164,fffbccfd8a08,ebad26,"The meat would smell sour but the would ""rub i...",1.771596,0.547742

In [6]:
summaries_df = pd.read_csv('../data/eval_student_summaries/summaries_train.csv')
summaries_df

,student_id,prompt_id,text,content,wording
0,000e8c3c7ddb,814d6b,The third wave was an experimentto see how peo...,0.205683,0.380538
1,0020ae56ffbf,ebad26,They would rub it up with soda to make the sme...,-0.548304,0.506755
2,004e978e639e,3b9047,"In Egypt, there were many occupations and soci...",3.128928,4.231226
3,005ab0199905,3b9047,The highest class was Pharaohs these people we...,-0.210614,-0.471415
4,0070c9e7af47,814d6b,The Third Wave developed rapidly because the ...,3.272894,3.219757
...,...,...,...,...,...
7160,ff7c7e70df07,ebad26,They used all sorts of chemical concoctions to...,0.205683,0.380538
7161,ffc34d056498,3b9047,The lowest classes are slaves and farmers slav...,-0.308448,0.048171
7162,ffd1576d2e1b,3b9047,they sorta made people start workin...,-1.408180,-0.493603
7163,ffe4a98093b2,39c16e,An ideal tragety has three elements that make ...,-0.393310,0.627128
7164,fffbccfd8a08,ebad26,"The meat would smell sour but the would ""rub i...",1.771596,0.547742

In [8]:
print(prompts_df['text'][0])

The third wave was an experimentto see how people reacted to a new one leader government. It gained popularity as people wanted to try new things. The students follow anything that is said and start turning on eachother to gain higher power. They had to stop the experement as too many people got to radical with it blindly following there leader

In [9]:
# 

# use list of stopwords from nltk
# stopwords = set(stopwords.words('english'))
# stopwords

In [11]:
lemmatizer = WordNetLemmatizer()

def lemmatize_words(string):
    words = string.split()
    words = [lemmatizer.lemmatize(word,pos='v') for word in words]
    return ' '.join(words)

In [12]:
def clean_text(df, column, column_new):
    """Removes non-alphabetic characters, converts to lowercase, removes stopwords, applies lemmatizer."""
    df[column_new] = df[column].apply(lambda x: re.sub('[^a-zA-Z]', ' ', x))
    df[column_new] = df[column_new].apply(lambda x: x.lower())
    df[column_new] = df[column_new].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))
    df[column_new] = df[column_new].apply(lemmatize_words)
    return df

In [15]:
prompts_df = clean_text(prompts_df, 'text', 'prompt_text_cl')

In [16]:
prompts_df

,student_id,prompt_id,text,content,wording,prompt_text_cl
0,000e8c3c7ddb,814d6b,third wave experimentto see people react new o...,0.205683,0.380538,third wave experimentto see people react new o...
1,0020ae56ffbf,ebad26,would rub soda make smell go away wouldnt bad ...,-0.548304,0.506755,would rub soda make smell go away wouldnt bad ...
2,004e978e639e,3b9047,egypt many occupations social class involve da...,3.128928,4.231226,egypt many occupations social class involve da...
3,005ab0199905,3b9047,highest class pharaohs people gods nd highest ...,-0.210614,-0.471415,highest class pharaohs people gods nd highest ...
4,0070c9e7af47,814d6b,third wave develop rapidly students genuinly b...,3.272894,3.219757,third wave develop rapidly students genuinly b...
...,...,...,...,...,...,...
7160,ff7c7e70df07,ebad26,use sort chemical concoctions make meat seem f...,0.205683,0.380538,use sort chemical concoctions make meat seem f...
7161,ffc34d056498,3b9047,lowest class slave farmers slave people take w...,-0.308448,0.048171,lowest class slave farmers slave people take w...
7162,ffd1576d2e1b,3b9047,sorta make people start work structour theyed ...,-1.408180,-0.493603,sorta make people start work structour theyed ...
7163,ffe4a98093b2,39c16e,ideal tragety three elements make ideal start ...,-0.393310,0.627128,ideal tragety three elements make ideal start ...
7164,fffbccfd8a08,ebad26,meat would smell sour would rub soda take away...,1.771596,0.547742,meat would smell sour would rub soda take away...

In [17]:
print(prompts_df['prompt_text_cl'][0])

third wave experimentto see people react new one leader government gain popularity people want try new things students follow anything say start turn eachother gain higher power stop experement many people get radical blindly follow leader